Manage sid at ~/.sevenri. Enhance the setup and clean scripts.
* setup: create Sevenri.app per instance by name
* setup: eliminate AppleScript file
* setup: can embed extra JVM opts using instance_name_SETUP_JVM_OPTS
* users can pass extra JVM opts using instance_name_JVM_OPTS at startup time

diff --git a/tools/clean b/tools/clean
--- a/tools/clean
+++ b/tools/clean
@@ -1,16 +1,56 @@
 #!/bin/bash
 
-if [ "$SEVENRI_PATH" = "" ]; then
-    SEVENRI_PATH=`pwd`
+# Print usage
+
+if [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
+    echo "usage: clean [-h|--help] [-i|--sid [instance_name]]"
+    exit 0
 fi
 
-if [ "$LEIN_CMD" = "" ]; then
-    LEIN_CMD=lein
+if [ "$SEVENRI_ROOT" == "" ]; then
+    SEVENRI_ROOT=`pwd`
 fi
+
+SevenriRoot=$SEVENRI_ROOT
+
+# Sanity check
+
+SevnriCljFileName="${SevenriRoot}/src/Sevenri.clj"
+
+if [ ! -f $SevnriCljFileName ]; then
+    echo "This script requires to run on a Sevenri repo root directory."
+    exit 1
+fi
+
+# Optionally cleanup sid
+
+if [ "$1" == "-i" ] || [ "$1" == "--sid" ]; then
+    if [ "$2" == "" ]; then
+        SevenriInstanceName="Sevenri"
+    else
+        SevenriInstanceName="Sevenri_$2"
+    fi
+else
+    SevenriInstanceName=""
+fi
+
+if [ "${SevenriInstanceName}" != "" ]; then
+    SIDPath=$HOME/.sevenri/$SevenriInstanceName
+fi
+
+# Leiningen command
+
+if [ "${LEIN_CMD}" = "" ]; then
+    LEIN_CMD="lein"
+fi
+
+LeinCmd=$LEIN_CMD
+
+# Helper functions
 
 debug_msg()
 {
-    if [ ${DEBUG_CLEAN_SEVENRI} ]; then
+    if [ $DEBUG_CLEAN_SEVENRI ]; then
         echo "DBG:" $1
     fi
 }
@@ -31,7 +71,7 @@ remove_file_type_on_path()
     local type="*.$1"
     local path="$2"
     debug_msg "find ${path} -name ${type} -delete"
-    find ${path} -name ${type} -delete
+    find $path -name $type -delete
 }
 
 clean_lein_project()
@@ -39,7 +79,7 @@ clean_lein_project()
     pushd $1 >/dev/null
 
     debug_msg "${LEIN_CMD} clean"
-    ${LEIN_CMD} clean >/dev/null
+    $LEIN_CMD clean >/dev/null
     remove_path ./lib
     remove_path ./pom.xml
 
@@ -48,50 +88,48 @@ clean_lein_project()
 
 main()
 {
-    print_msg "== Remove .sevenri paths =="
-    for dot_sevenri in `echo .sevenri*`
-    do
-        print_msg $dot_sevenri
-        remove_path ./$dot_sevenri
-    done
-
-    print_msg "== Clean the Sevenri project =="
+    print_msg "Cleaning the Sevenri project..."
     clean_lein_project .
 
-    print_msg "== Remove src/library paths =="
+    print_msg "Removing src/library paths..."
     for path in "clojure" "incanter" "slix/incantea/data"
     do
         print_msg $path
         remove_path ./src/library/$path
     done
 
-    print_msg "== Remove src/sevenri paths =="
+    print_msg "Removing src/sevenri paths..."
     for path in "listeners/evtdelegator"
     do
         print_msg $path
         remove_path ./src/sevenri/$path
     done
 
-    print_msg "== Remove .class files on src/sevenri/listeners =="
+    print_msg "Removing .class files on src/sevenri/listeners..."
     remove_file_type_on_path "class" ./src/sevenri/listeners
 
-    print_msg "== Remove src/slix paths =="
+    print_msg "Removing src/slix paths..."
     for path in "sevenri/jvm/gui/bin"
     do
         print_msg $path
         remove_path ./src/slix/$path
     done
 
-    print_msg "== Clean src/project/slix projects =="
+    print_msg "Cleaning src/project/slix projects..."
     for project in "documenter" "incantea" "planter"
     do
         print_msg $project
         clean_lein_project ./src/project/slix/$project
     done
+
+    if [ $SIDPath ]; then
+        print_msg "Removing Sevenri instance directory: $SIDPath..."
+        remove_path $SIDPath
+    fi
 }
 
-# Start cleaning up stuff on ${SEVENRI_PATH}
+# Start cleaning up stuff on $SevenriRoot
 
-pushd ${SEVENRI_PATH} >/dev/null
+pushd $SevenriRoot >/dev/null
 main
 popd >/dev/null
diff --git a/tools/setup b/tools/setup
--- a/tools/setup
+++ b/tools/setup
@@ -1,11 +1,88 @@
 #!/bin/bash
-sa=./Sevenri.app
 
-if [ -a $sa ]; then
-	rm -rf $sa
+# Print usage
+
+if [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
+    echo "usage: setup [-v|--verbose|-h|--help] [instance_name]"
+    echo "Use the instance_name_SETUP_JVM_OPTS environment variable"
+    echo "to preset extra JVM options."
+    exit 0
 fi
 
-osacompile -o $sa -x tools/Sevenri.scpt >/dev/null 2>&1
-cp tools/Sevenri-icon.icns $sa/Contents/Resources/applet.icns
+# Sanity check
 
+SevnriCljFileName=./src/Sevenri.clj
+SevenriIconFileName=./src/resources/images/icons/Sevenri-icon.icns
+
+if [ ! -f $SevnriCljFileName ] || [ ! -f $SevenriIconFileName ]; then
+    echo "This script requires to run on a Sevenri repo root directory."
+    exit 1
+fi
+
+# SevenriRoot: current directory where is a Sevenri repo root directory
+# SevenriInstanceName: a Sevenri instance name; "Sevenri" by default
+
+SevenriRoot=`pwd`
+
+if [ "$1" == "" ]; then
+    SevenriInstanceName="Sevenri"
+elif [ "$1" == "-v" ] || [ "$1" == "--verbose" ]; then
+    verbose=true
+    if [ "$2" == "" ]; then
+        SevenriInstanceName="Sevenri"
+    else
+        SevenriInstanceName="Sevenri_$2"
+    fi
+else
+    SevenriInstanceName="Sevenri_$1"
+fi
+
+# Prepare for creating a Sevenri.app from an AppleScript
+
+SevenriAppFileName="./${SevenriInstanceName}.app"
+
+if [ "$TMPDIR" == "" ]; then
+    TMPDIR=./tools
+fi
+
+TempAppleScriptFileName="${TMPDIR}/${SevenriAppFileName}.applescript.tmp"
+
+# JavaVM options
+DefaultSetupJVMOptions="-Dfile.encoding=UTF-8 -Dsevenri.sid.name=$SevenriInstanceName "
+SetupJVMOptsEnvVarName="${SevenriInstanceName}_SETUP_JVM_OPTS"
+SetupJVMOptions="${DefaultSetupJVMOptions}${!SetupJVMOptsEnvVarName}"
+RuntimeJVMOptsEnvVarName="\$${SevenriInstanceName}_JVM_OPTS"
+
+read -d '' script <<EOF
+set cmd to "cd $SevenriRoot
+if [ -f \$HOME/.bash_profile ]; then
+    source \$HOME/.bash_profile
+fi
+java $SetupJVMOptions $RuntimeJVMOptsEnvVarName -cp src:lib/* Sevenri &>/dev/null &"
+do shell script cmd
+EOF
+
+if [ -a $SevenriAppFileName ]; then
+	rm -rf $SevenriAppFileName
+fi
+
+# Start setting up staff.
+
+echo "Creating $SevenriInstanceName.app..."
+
+if [ "$verbose" == "true" ]; then
+    echo "AppleScript used..."
+    echo ">>>"
+    echo "$script"
+    echo "<<<"
+    echo
+fi
+
+# Double-quote $script to preserve \newline.
+echo "${script}">$TempAppleScriptFileName
+osacompile -o $SevenriAppFileName -x $TempAppleScriptFileName >/dev/null 2>&1
+rm $TempAppleScriptFileName
+cp $SevenriIconFileName $SevenriAppFileName/Contents/Resources/applet.icns
+
+echo "Downloading required dependencies..."
 lein deps
